# ~/.config/yazi/yazi.toml

[open]
rules = [
    #media and documents
    { name = "*/", use = [ "edit", "open", "reveal" ] },
    { mime = "video/*", use = "play" },
    { name = "*.mkv", use = "play" },
    { name = "*.mp4", use = "play" },
    { name = "*.webm", use = "play" },
    { mime = "application/pdf", use = "pdf" },
    { mime = "image/*", use = "image" },
    { name = "*.odt", use = "office" },
    { name = "*.docx", use = "office" },
    { name = "*.xlsx", use = "office" },
    { name = "*.pptx", use = "office" },
    { name = "*.html", use = "web" },
    { name = "*.htm", use = "web" },

    #program and config files to open in nvim
    { name = "*.json", use = "edit" },
    { name = "*.jsonc", use = "edit" },
    { name = "*.toml", use = "edit" },
    { name = "*.yaml", use = "edit" },
    { name = "*.yml", use = "edit" },
    { name = "*.ini", use = "edit" },
    { name = "*.conf", use = "edit" },
    { name = "*.lua", use = "edit" },
    #git files
    { name = ".gitignore", use = "edit" },
    { name = ".gitconfig", use = "edit" },
    { name = ".gitmodules", use = "edit" },
    #build systems
    { name = "CMakeLists.txt", use = "edit" },
    { name = "*.cmake", use = "edit" },
    { name = "Makefile", use = "edit" },
    { name = "Justfile", use = "edit" },
    #programming languages 
    { name = "*.c", use = "edit" },
    { name = "*.cpp", use = "edit" },
    { name = "*.h", use = "edit" },
    { name = "*.hpp", use = "edit" },
    { name = "*.rs", use = "edit" },
    { name = "*.java", use = "edit" },
    { name = "*.py", use = "edit" },
    { name = "*.js", use = "edit" },
    { name = "*.ts", use = "edit" },
    { name = "*.css", use = "edit" },
    { name = "*.sh", use = "edit" },
    { name = "*.zsh", use = "edit" },

    #fallback for other program files
    { mime = "text/*", use = "edit" },
    { mime = "application/json", use = "edit" },
    { mime = "application/javascript", use = "edit" },
    { mime = "application/x-shellscript", use = "edit" },
    { mime = "empty", use = "edit" },
    { name = "*", use = "fallback" },

    #archives
    { mime = "application/zip", use = "archive" },
    { mime = "application/gzip", use = "archive" },
    { mime = "application/x-tar", use = "archive" },

		#images
		{ mime = "image/*", use = "view" }

]
