#open all text files in my nvim
mime ^text, = nvim "$@"


#for videos
mime video/, has mpv, = mpv -- "$@"
ext mkv|mp4|webm, has mpv, = mpv -- "$@"


#for pdf files
ext pdf, has zathura, = zathura "$@"
ext pdf, has mupdf, = mupdf "$@"


#for images
mime image/, has swayimg, = swayimg "$@"
mime image/, has imv, = imv "$@"
mime image/, has feh, = feh "$@"


#for additional files with weird extensions
ext odt|ods|odp|docx|xlsx|pptx|ppt, has libreoffice, = libreoffice "$@"


#for web files
ext html|htm, has firefox, = firefox "$@"
ext html|htm, has chromium, = chromium "$@"

#for my archive files
# list contents
ext 7z|ace|ar|arc|bz2?|cab|cpio|cpt|deb|dgc|dmg|gz|iso|jar|lha|lz|lzh|lzma|lzo|rpm|rz|t7z|tar|tbz2?|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|zip, has atool = atool --list --each -- "$@" | less

#extract here
label extract, ext 7z|ace|ar|arc|bz2?|cab|cpio|cpt|deb|dgc|dmg|gz|iso|jar|lha|lz|lzh|lzma|lzo|rpm|rz|t7z|tar|tbz2?|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|zip, has atool = atool --extract --each -- "$@"


#execute python/shell scripts in my terminal or current one
ext py,  terminal = python -- "$1"
ext pl,  terminal = perl -- "$1"
ext rb,  terminal = ruby -- "$1"
ext js,  terminal = node -- "$1"
ext sh,  terminal = sh -- "$1"
