# --- Open all text files in Neovim ---
mime ^text, = nvim "$@"


# --- for videos ---
mime video/, has mpv, = mpv -- "$@"
ext mkv|mp4|webm, has mpv, = mpv -- "$@"


# --- for pdf files ---
ext pdf, has zathura, = zathura "$@"
ext pdf, has mupdf, = mupdf "$@"


# --- for images ---
mime image/, has swayimg, = swayimg "$@"
mime image/, has imv, = imv "$@"
mime image/, has feh, = feh "$@"


# --- for additional files with weird extensions ---
ext odt|ods|odp|docx|xlsx|pptx|ppt, has libreoffice, = libreoffice "$@"


# --- for web files ---
ext html|htm, has firefox, = firefox "$@"
ext html|htm, has chromium, = chromium "$@"


# --- idk ---
* = atool --list "$@"
* = less -R "$@"

