animations {
    enabled = true
    animation = fadeIn, 1, 3.5, linear
    animation = fadeOut, 1, 3.5, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 5
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
}
# clock display
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = rgba(220, 240, 245, 0.95)
    font_size = 80
    font_family = FantasqueSansM Nerd Font Bold
    position = 0, 100
    halign = center
    valign = center
}
# media and date fallback display
label {
    monitor =
    text = cmd[update:2000] bash /home/mocha/.config/hypr/scripts/media-status.sh
    color = rgba(220, 240, 245, 0.85)
    font_size = 15
    font_family = FantasqueSansM Nerd Font
    position = 0, 30
    halign = center
    valign = center
}
# input area
input-field {
    monitor =
    size = 220, 36
    outline_thickness = 1
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    rounding = -1
    inner_color = rgba(255, 255, 255, 0.20)
    outer_color = rgba(255, 255, 255, 0.35)
    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    placeholder_text = <span foreground="##ffffffaa" font_family="FantasqueSansM Nerd Font">Enter Password</span>
    hide_input = false
    position = 0, -26
    halign = center
    valign = center
}
# todo.sh display carrousel
label {
    monitor =
    text = cmd[update:5000] bash /home/mocha/.config/hypr/scripts/todo-carousel.sh
    color = rgba(220, 240, 245, 0.75)
    font_size = 14
    font_family = FantasqueSansM Nerd Font
    position = 0, 40
    halign = center
    valign = bottom
}
